/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fdf7ff',
        'on-background': '#1d1b20',
        surface: '#fdf7ff',
        'surface-dim': '#ded8e0',
        'surface-bright': '#fdf7ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8f2fa',
        'surface-container': '#f2ecf4',
        'surface-container-high': '#ece6ee',
        'surface-container-highest': '#e6e0e9',
        'on-surface': '#1d1b20',
        'on-surface-variant': '#494551',
        'inverse-surface': '#322f35',
        'inverse-on-surface': '#f5eff7',
        outline: '#7a7582',
        'outline-variant': '#cbc4d2',
        'surface-tint': '#6750a4',
        primary: '#4f378a',
        'on-primary': '#ffffff',
        'primary-container': '#6750a4',
        'on-primary-container': '#e0d2ff',
        'inverse-primary': '#cfbcff',
        secondary: '#63597c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1d4fd',
        'on-secondary-container': '#645a7d',
        tertiary: '#765b00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c9a74d',
        'on-tertiary-container': '#503d00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['"Source Sans 3"', 'sans-serif'],
        serif: ['"Playfair Display"', 'serif'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'container-padding': '16px',
        'gutter': '16px',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
